[openai]
# 获取地址：https://platform.openai.com/account/api-keys
api_key="sk-xx"

[auth]
# 这个不要改
cookie_key="ai_cookie"

# 授权的暗号列表，多个以空格隔开。认证通过会使用 [openai].api_key 进行对话。
valid_cookies="easyai-xx"

# 设定密码，认证通过会使用 [openai].api_key 进行对话。
password=""